layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: stars
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  linkedin: d3rise
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  telegram: d3rise
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: https://derise.pw/
  # youtube: your_username

topics:
    - name: TypeScript
      web_url: https://www.typescriptlang.org/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/typescript/typescript.png
      
    - name: Python
      web_url: https://www.python.org/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/python/python.png
    
    - name: Node.js
      web_url: https://nodejs.org/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/nodejs/nodejs.png
    
    - name: Django
      web_url: https://www.djangoproject.com/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/django/django.png
      
    - name: Celery
      web_url: https://celeryproject.org/
      image_url: https://docs.celeryproject.org/en/stable/_static/celery_512.png
      
    - name: Express
      web_url: https://expressjs.com/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/express/express.png

    - name: Nest.js
      web_url: https://nestjs.com/
      image_url: https://d33wubrfki0l68.cloudfront.net/e937e774cbbe23635999615ad5d7732decad182a/26072/logo-small.ede75a6b.svg

    - name: Linux
      web_url: https://www.linux.org/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/linux/linux.png
      
    - name: PostgreSQL
      web_url: https://www.postgresql.org/
      image_url: https://upload.wikimedia.org/wikipedia/commons/2/29/Postgresql_elephant.svg
      
    - name: MongoDB
      web_url: https://www.mongodb.com/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/mongodb/mongodb.png

    - name: Git
      web_url: https://git-scm.com/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/git/git.png

    - name: Redis
      web_url: https://redis.io/
      image_url: https://raw.githubusercontent.com/github/explore/80688e429a7d4ef2fca1e82350fe8e3517d3494d/topics/redis/redis.png

    - name: RabbitMQ
      web_url: https://www.rabbitmq.com/
      image_url: https://www.rabbitmq.com/img/logo-rabbitmq.svg
